### ISSUE TITLE
Retrieving document on filename or hash

### ISSUE THREAD

**Issue by ProCessor00** [thalpius/Incident-Response-Microsoft-365#1]
A function to retrieve an email attachment by filename or hash would be great!

**Comment by thalpius** [comment]
Thank you for raising an issue. You can use the function "thalpiusGetAttachments" to get all filenames. Unfortunately, there is no hash from the output, but you can get the base64 encoded string for the attachment using the function "thalpiusGetAttachments". From there you can calculate the hash if needed. So everything you need is in this script.

**Comment by thalpius** [comment]
I've added the function some weeks ago. It's slow, but it's working.
